### ISSUE TITLE
Email Notification of Departing Controller to the FIR Management

### ISSUE THREAD

**Issue by mgwalsh99** [VATSIMCanada/issue-tracker#1]
When a controller leaves/transfers from an FIR, the departing FIR is unaware that this has occurred.  This creates internal FIR issues whereby the local roster has to be adjusted to reflect that the controller is no longer a controller with the FIR.

When a member applies for a transfer to another FIR, the departing FIR management is notified.

When a member has successfully transferred to another FIR, the departing FIR management is notified.

This would also apply for members departing the division.

**Comment by JordannDev** [comment]
I'll make this a priority item, and try and get this done soon. Will be in the next release of the site.

**Comment by xLostShadows** [comment]
As far as I know, this is still an issue. Will be fixed soon

**Comment by xLostShadows** [comment]
I believe this is resolved. Going to close
