### ISSUE TITLE
[BUG] Assigned students moved to academy stuck in students list

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#10]
**Describe the bug**
From Thomas from Edmonton. 

We had a student (Trevor 1562269) who was assigned to him as a student.  When Trevor was moved to the academy last July he to this day remains stuck in Thomas' student list.   I have tried to force academy on Trevor but no luck.

**To Reproduce**
1. Assign a student to an instructor
2. Send to academy. 
3. See student stuck in assigned students list

**Expected behavior**
Students going to the academy should have an error if assigned to an ins ... or that assignment should be revoked automatically. 

Thanks!

**Comment by xLostShadows** [comment]
In progress

**Comment by xLostShadows** [comment]
Resolved

**Comment by xLostShadows** [comment]
Resolved
