### ISSUE TITLE
[FEATURE] Training Note added to Categories

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#12]
**Is your feature request related to a problem? Please describe.**
From Jagard Strong:
Any chance we can get the category " Training Note" added to the drop down list of session types in training?

**Describe the solution you'd like**
On the website when entering a training note for a student the dropdown for Session Type (Sweatbox,  OJT, OTS)  can we add an additional option for "Training Note"

**Comment by xLostShadows** [comment]
In progress
