### ISSUE TITLE
[FEATURE] Student Un-Assignment on roster removal

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#13]
**Is your feature request related to a problem? Please describe.**
Students become stuck in an instructor's list of students when that controller is removed from the roster (sent to academy / suspected etc) 

**Describe the solution you'd like**
If possible it would ideal for this assignment to be removed when the controller is removed from an FIR.   Failing that have a warning to the roster manager that when they send to academy that the student still has an instructor assigned.

**Comment by xLostShadows** [comment]
Duplicate issue
