### ISSUE TITLE
[Feature] Solo Endorsements - Requirement for GCAP

### ISSUE THREAD

**Issue by mgwalsh99** [VATSIMCanada/issue-tracker#16]
Changes to the Solo Endorsements.

Technically now, the SOLO is three solos, 30 days for a max of 90 days.   

GCAP now authorizes 7 days to a max of 90 days for one Solo cert.  All solo certs cannot extend beyond 90 days.  

In addition, a solo extension period can be authorized for a max of 30 days.  The Division Director has to seek permission from the VP of Americas to extend 30 day periods. So something that vatcan1, 2 or 3 can use to extend the solo to max 30 day increments.   

A reset button for Vatcan executive (1,2,3) to reset the 90 days period completely based on 7.3(d).

**Comment by xLostShadows** [comment]
@mgwalsh99 So, if 1 year has passed since the expiry of the solo cert, you don't need permission from VP AMA? Am I reading that right?

**Comment by mgwalsh99** [comment]
GCAP - 7.3(d) Notwithstanding the above, the 90-day limit shall be reset if a controller transfers
Division and restarts training in their new Division or if a controller re-enters training
having not received any training or a solo endorsement for a period of 1 year or
greater.

7.3(e) In exceptional circumstances, a Region Vice President may approve a 30-day
extension to a solo endorsement.

**Comment by xLostShadows** [comment]
Complete
