### ISSUE TITLE
[BUG] Support - Membership Tickets

### ISSUE THREAD

**Issue by mgwalsh99** [VATSIMCanada/issue-tracker#17]
**Describe the bug**
Bug #1 - Sometimes a support ticket is entered and when you try to open it, it generates a server error and unable to read or action the ticket.

Bug #2 - Once all the support tickets are closed, clicking on the open/all tickets button will NOT display all the tickets.  Nothing will be displayed.

**Comment by xLostShadows** [comment]
Will look into this.
