### ISSUE TITLE
Add email to the Transfer Screen

### ISSUE THREAD

**Issue by mgwalsh99** [VATSIMCanada/issue-tracker#2]
When a transfer is requested and the accepting manager looks at the transfer screen where you can either approve or reject the transfer, it would be beneficial to have the email address also listed.  This assists the accepting manager to complete the FIRs roster and also helps in sending a welcome message. Example attached.
![Capture](https://user-images.githubusercontent.com/49923415/207883027-d6dfab50-00b9-46a2-837f-7fc280304e6e.JPG)

**Comment by JordannDev** [comment]
This can be added, but it's somewhat redundant, The "View User" button will bring you to the Controller Management page which includes their email. 

It's also worth noting when an FIR pulls its roster from the API it includes the Controller's Email, so the need for a manual process (adding people to the roster) should be fairly minimal. 

API docs can be found [here](https://api.vatcan.ca), I'll add this item to the list but it's low priority

**Comment by JordannDev** [comment]
Added and will be included in the next release.
