### ISSUE TITLE
[FEATURE] Additions to the Statistics Page

### ISSUE THREAD

**Issue by mgwalsh99** [VATSIMCanada/issue-tracker#22]
Currently Exams only show a Percentage of Failures, however we don't know where the problem areas are.  
Update the page so that the exam stats are based on each S1,S2,S3,C1 rating exams (Failure/pass rates in %) per quarter. 

Currently the division only shows how many members in Vatcan hold individual ratings.  Would like to see the Individual FIR rating counts below the division rating count.
i.e. 
CZAE INAC | SUSP | OBS | S1 | S2 | S3 | C1 | C2 | C3 | I1 | I2 | I3 | SUP | ADM
          2 | 0 | 0 | 208 | 34 | 19 | 45 | 0 | 17 | 21 | 0 | 16 | 6 | 2
CZVR 0 | 0 | 0 | 5 | 24 | 19 | 45 | 0 | 17 | 21 | 0 | 16 | 6 | 2
CZEG etc....

**Comment by xLostShadows** [comment]
Complete
