### ISSUE TITLE
Exam Reassignment Value

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#3]
**Describe the bug**
Vancouver FIR has opted to set their local exams to a 3 days wait window instead of 7 for a student that fails.
Their exams have set the setting "Retake Days" to 3. 

The result is if the student fails, they will get an email saying 3 days to retake but the actual value the system goes to is 7.  

**To Reproduce**
1. Go to https://vatcan.ca/manage/training/exams/edit/32
2. See setting 
3. ...  fail test somehow?
4. Profit!

**Expected behavior**
Ideally the value should show up in both the email and actual date the student can retake.

**Additional context**
Lets go Blue Jays!!

**Comment by JordannDev** [comment]
This has been fixed and will be included in the next release.

**Comment by codeman02** [comment]
Hey Jordan, 

Can you confirm the website is on a release where this issue was included?   
I just received a member ticket complaining on this issue. 

Welcome back from vacation :D
