### ISSUE TITLE
[FEATURE] FIR Removal Procedure

### ISSUE THREAD

**Issue by mgwalsh99** [VATSIMCanada/issue-tracker#34]
With the onset of GCAP, the Removal Feature for the FIRs need to be modified.   

Procedure:
1) FIR Chief or delegate clicks the Remove Controller Button
2) Brings up another page that gives options
3) Options include - 
    a) Remove due to currency  
    b) Remove at Controllers Request 
    c) Remove - Other
---- if a or b as above, FIR attests that this is correct and not being used for any other purpose and the controller is removed from the FIR without the need of Vatcan Exec involvement.
4) Notification is sent to Vatcan1 and Vatcan2
5) Vatcan Exec has the ability to enter comments in a box in compliance with removal policy and hits either the Approve or Reject button for the request.

**Comment by xLostShadows** [comment]
Complete - will release when approved
