### ISSUE TITLE
[BUG] Broken Membership Ticket

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#7]
**Describe the bug**

https://vatcan.ca/my/membership/staff/97
Open | s1 exam | keruler kifer | No Staff Assigned | 2022-06-22

This ticket from June goes to a trouble page when we try to open it.  Can you please delete the ticket as we have not answered and its been 6 months.

**Comment by JordannDev** [comment]
User was removed in a GDPR Request but the ticket remained after they were removed. I deleted the ticket, should be good to go.
