### ISSUE TITLE
[FEATURE]  OTS Exams Online Form

### ISSUE THREAD

**Issue by codeman02** [VATSIMCanada/issue-tracker#8]
**Is your feature request related to a problem? Please describe.**
Presently the Instructors across multiple FIR's utilize a PDF form to conduct marking for OTS's then attach that form to the training note.  Phil, Mark and I were looking at some of the variants this form took when FIRs tried to brand it and modified the fields and would like to see a common online form instead that we have control over. 

**Describe the solution you'd like**
Ideally, an instructor that is about to preform an OTS can go to the training notes, click new, and select OTS.  From there it should launch into the form where we can fill out and score the OTS/leave comments etc.   Because its an online form ideally the marking Instructor should be able to get back into it and modify it at anytime (IE if their browser closed)  and have edit rights up until the form is submitted. The existing forms today can be found here:
S2 - https://canada.ams3.digitaloceanspaces.com/core/documents/OTSMarkingSheetS2.pdf
S3 - https://canada.ams3.digitaloceanspaces.com/core/documents/OTSMarkingSheetS3.pdf
C1 - https://canada.ams3.digitaloceanspaces.com/core/documents/OTSMarkingSheetC1.pdf

**Comment by JordannDev** [comment]
@kolbyd I think we discussed this a while ago, we could come up with a setup similar to how we have exams currently (serialize/deserialize JSON) to allow for them to be modified easily and that would also allow for drafts. What do you think?

**Comment by codeman02** [comment]
Yeah I would love to see it!   Only random thing I could suggest would be the possibility of forcing a written comment when someone scores something lower then 2?     Otherwise the test format would be great. 

Thanks Jordan and Kolby!

**Comment by xLostShadows** [comment]
This will definitely be added. I believe all forms should require comments, regardless of score. @mgwalsh99 Thoughts?

**Comment by mgwalsh99** [comment]
It can be added, similar to that of the exam questions module.  Comments as to why such a low score should be qualified.

**Comment by mgwalsh99** [comment]
On Hold pending the outcome of new OTS templates by Vatcan3.  Consideration to be added later so that real stats can be pulled out.

**Comment by xLostShadows** [comment]
Complete
