### ISSUE TITLE
Ability to manually add notes (with images) on a members record.

### ISSUE THREAD

**Issue by pdowling1973** [VATSIMCanada/issue-tracker#9]
Which would also be filtered under it's own tab away from the automated website updates to the record.  In order to record disciplinary issues and any other issues as needed.  (We talked about this Jordan)

**Comment by xLostShadows** [comment]
New tab will be added to user page. **System Log** will contain any website automations. **Action Log** will contain any current and/or past disciplinary action.

**Comment by xLostShadows** [comment]
This already exists
